name: Verify

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-16.04
    timeout-minutes: 40

    strategy:
      fail-fast: true
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
        test_cmd:
          - bundle exec rake spec
          - bundle exec rake cucumber
          - bundle exec rake yard

    env:
      RAILS_ENV: test

    name: Ruby ${{ matrix.ruby }} - ${{ matrix.test_cmd }}
    steps:
      - name: Install system dependencies
        run: sudo apt-get install graphviz

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup bundler
        run: |
          gem install bundler

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        env:
          BUNDLER_WITHOUT: coverage development pcap

      - name: ${{ matrix.test_cmd }}
        run: |
          echo "${CMD}"
          bash -c "${CMD}"
        env:
          CMD: ${{ matrix.test_cmd }}

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-${{ matrix.ruby }}
          path: |
            coverage/
          retention-days: 1
